// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GithubRepositoryStats
{
    internal sealed partial class Vsix
    {
        public const string Id = "GithubRepositoryStats.9ad7b95a-52c7-4a5c-9c72-af6c9c28ab29";
        public const string Name = "GithubRepositoryStats";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "saman azadi";
        public const string Tags = "";
    }
}
